

spring:
  profiles:
    active: dev

---
#开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&useSSL=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 60
      minimum-idle: 10
      connection-test-query: SELECT 1
      connection-timeout: 3000
      idle-timeout: 600000
      maxLifetime: 1800000
      read-only: false

server:
  port: 1000

mybatis:
  typeAliasesPackage: com.example.learn.pojo
  mapper-locations: classpath:mappers/*.xml


---
#测试环境配置
spring:
  profiles: test

server:
  port: 1001


---
#生产环境配置
spring:
  profiles: prod

server:
  port: 1002
